<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPOAz53H\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPOAz53H/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPOAz53H.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPOAz53H\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPOAz53H\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'POAz53H',
    'container.build_id' => 'ca21aea1',
    'container.build_time' => 1557732478,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPOAz53H');
