<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4oS3NYr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4oS3NYr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4oS3NYr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4oS3NYr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container4oS3NYr\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '4oS3NYr',
    'container.build_id' => 'c5f39a4a',
    'container.build_time' => 1559811162,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4oS3NYr');
