<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE0KAWha\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE0KAWha/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE0KAWha.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE0KAWha\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerE0KAWha\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'E0KAWha',
    'container.build_id' => '33689b11',
    'container.build_time' => 1557998538,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE0KAWha');
